apps/landing/urls.py
# coding=utf-8
from django.conf.urls import url, include

from .views import LandingView, OkView

urlpatterns = [
    url(r'^$', LandingView.as_view(), name='index'),
    url(r'^ok/$', OkView.as_view(), name='ok'),
]

cms/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'', include('apps.landing.urls', namespace='website')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'ticket/', include('apps.ticket.urls', namespace='ticket')),
    url(r'download/', include('apps.download.urls', namespace='download')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi aperiam, aspernatur consectetur dignissimos distinctio eum eveniet explicabo iste magnam minima nesciunt, non nulla officia qui repellendus reprehenderit sint vero voluptates.
</body>
</html>

templates/ok.html
{% extends 'index.html' %}
{% block top_js %}
	<script type="text/javascript">
		setTimeout('location.replace("{% url 'website:index' %}")', 3000);
	</script>
  <style>
  html, body, .franchise-first {
    height: 100%;
  }
  .parent {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow: auto;
    white-space: nowrap;
    text-align: center;
    font-size: 0;
  }
  .parent:before {
        height: 100%;
        display: inline-block;
        vertical-align: middle;
        content: '';
    }


  .block {
      display: inline-block;
      white-space: normal;
      vertical-align: middle;
      text-align: left;
  }
  </style>
{% endblock %}
{% block header %}
{% endblock %}
{% block content %}
  <section class="franchise-first">
    <div class="parent">
      <div class="block">
        <div class="container_12">
          <div class="franchise-first-container">
            <div class="grid_7">
              <h2 class="franchise__title franchise__title_blue">ВАША ЗАЯВКА ПРИНЯТА!</h2>
              <h2 class="franchise__title">в течение суток мы пришлём вам индивидуальное предложение</h2>
            </div>
            <div class="clearfix"></div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}